---
environment: production
logger:
  development: true
  level: "debug"
  encoding: "console"
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
    # initialFields:
  # initFieldKey: "fieldValue"
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    nameKey: "logger"
    timeKey: "time"
    callerKey: "logger"
    stacktraceKey: "stacktrace"
    callstackKey: "callstack"
    errorKey: "error"
    timeEncoder: "iso8601"
    fileKey: "file"
    levelEncoder: "capital"
    durationEncoder: "second"
    callerEncoder: "short"
    nameEncoder: "short"
      # sampling:
      # initial: "3"
    # thereafter: "10"
  profiler:
    enable: true
database:
  driverName: "mysql"
  dataSourceName: "cms@iot-mysql-device-layer-sercomm-cicd:ability123@tcp(iot-mysql-device-layer-sercomm-cicd.mysql.database.azure.com)/n_cms_core?charset=utf8"
  maxOpenConns: 10
  maxIdleConns: 10
  # the unit of connMaxLifetime is minute.
  connMaxLifetime: 180
redis:
  mode: "single"
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  readTimeout: 6000
  writeTimeout: 6000
  retryAttempts: 3
  retryInterval: 1500
  password: "xStKdsivvrnAm8kZatJst0982NWJQx4fj137WyQkCzg="
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 32
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 32
  masterConnectionPoolSize: 800
  readMode: "MASTER"
  subscriptionMode: "SLAVE"
  nodeAddresses: "iot-redis-device-layer-evo-sercomm-dev.redis.cache.windows.net:6379"
  scanInterval: 1000
  pingConnectionInterval: 600000
  keepAlive: false
coap:
  normalPort: ":5683"
  dtlsPort: ":5684"
  gRPCPort: ":50051"
  restPort: ":28080"
  timestampLayout: "2006-01-02T15:04:05.000Z"
  timestampLayouts:
  - "2006-01-02T15:04:05.000Z"
  - "06/01/02,15:04:05-07"
  psk: "ability123"
  messageTTL: 35
  nameSpace: "nbiot:taiyofota"
  sessionKeepAlive: 0
  aes128Ecb:
    secretKey: ""
    padding: "pkcs7"
fwUpgrade:
  maxConcurrent: 60
  sendBytesPerQuery: 512
  keyDeleteDelay: 60
  timeout: 300  # seconds
grpc:
  queryTimeout: 10 # seconds
